export * from './waste-sources.controller';
export * from './waste-types.controller';
export * from './treatment-plants.controller';
export * from './water-quality-lab-reports.controller';
export * from './water-quality-parameters.controller';
export * from './storage-locations.controller';
export * from './monthly-flow-reports.controller';
export * from './weight-reports.controller';
export * from './dispatch-orders.controller';
